### ISSUE TITLE
[dev] Subtitles not showing fully at first - works after a window resize or fulscreen action

### ISSUE THREAD

**Issue by PROJEKTILES** [mfpaccessibilite/MFP_AccessPlayer#10]
Subtitles only show first line when activated (except STL wich show correctly).
After a windows resize, or a switch to fullscreen and back to normal, subtitles show correctly the 2 lines.

**Comment by mfpaccessibilite** [comment]
Tested on Firefox 59.0.2 - macos 10.11.6 + xUbuntu 16.0.4
