### ISSUE TITLE
[Dev] Transcription en temps réel donnée uniquement par la couleur

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#11]
La transcription en temps réel indique par la couleur rouge la position de la narration.

> [Critère 3.1 [A] Dans chaque page web, l'information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-3-1)

Remplacer la couleur rouge du texte par un élément graphique comme une surbrillance via une balise `<mark>` ou à l'aide d'un `<span>` avec un background (#FF6) pour marquer la position de la narration.

**Comment by simchaba** [comment]
Le live subtitle est wrap dans un <mark>

**Comment by ldzintegratore** [comment]
Je n'ai pas saisi le commentaire non terminée, pouvez-vous le compléter svp ?

**Comment by simchaba** [comment]
Le live Subtitle est wrap dans un <mark> à présent

**Comment by ldzintegratore** [comment]
Je crains de ne pas comprendre. L'idée est de remplacer le texte rouge par un surlignement avec background : #FF6 par exemple.

**Comment by simchaba** [comment]
Il m'a semblé que la demande était de mettre une balise autour du sous-titre live en plus de l'ajout d'une classe permettant son changement de couleur afin de refléter l'état dans le DOM. C'est à présent le cas. Le sous-titre lorsque c'est celui affiché est dans un une balise <mark> comme demandé

**Comment by ldzintegratore** [comment]
c'est bien ça, il faudrait rajouter le surlignement demandé du coup, merci
