### ISSUE TITLE
[Dev] Non restitution à la vocalisation du lecteur d'écran de l'état activé/désactivé des boutons [AD], [Langue des signes], [CC] dans les tooltip et les title

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#12]
L'indication de l'état actif/non-actif des boutons [AD], [Langue des signes], [CC] et [Versions textes de la vidéo] par la couleur n'est pas suffisante.

> [Critère 3.1 [A] Dans chaque page web, l'information ne doit pas être donnée uniquement par la couleur. Cette règle est-elle respectée ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-3-1)

Indiquer l'état des boutons (activé/desactivé) dans les textes cachés, les `title` et les tooltips :
Lorsque l'audio-description n'est pas activé, indiquer "Activer audio-description".
Lorsque l'audio-description est activé, indiquer "Désactiver audio-description" etc...

**Comment by ldzintegratore** [comment]
#8

**Comment by simchaba** [comment]
L'état des boutons est à présent mis à jour
