### ISSUE TITLE
[Dev] Listbox du bouton [CC]

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#14]
Au clic sur le bouton [CC] une fenêtre de dialog affiche une listbox et vocalise qu’il existe 3 éléments de liste. Quand on active le 3e élément, la synthèse vocale vocalise « Français (personnalisable) » 3 sur 3 **mais rien n’indique qu’il est possible d’accéder aux paramètres de personnalisation des sous-titres**.
> [Critère 7.1 [A] Chaque script est-il, si nécessaire, compatible avec les technologies d'assistance ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-7-1) 

Il faudrait ajouter une relation parent/enfant avec un attribut `aria-owns` sur l'élément de liste "Français (personnalisable)" et un `ID` sur l'élément de liste "Personnalisation des sous-titres"
Ex :
```
<ul>
...
<li aria-owns="custom" data-id="1" role="option" tabindex="-1" class="">Français (personnalisable)</li>
<li id="custom" class="preferences" style="display: none;" role="option" tabindex="-1">Personnalisation des sous-titres <span class="mfp-icon-pref"></span></li>
</ul>
```

**Comment by simchaba** [comment]
Un lien aria-owns a été ajouté, cependant 2 éléments du menu peuvent avoir ce aria-owns si ces 2 fichiers sont de format .srt
