### ISSUE TITLE
[Dev] Dissocier affichage Transcript temps réel du sous-titrage pour permettre un affichage indépendant

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#15]
Actuellement le transcript temps réel n'est disponible qu'à l'activation des sous-titres. 
Pour plus de souplesse et de compréhension, il serait intéressant de dissocier cette fonctionnalité afin qu'elle soit indépendante et activable/désactivable simplement, en cas de nécessité.

**Comment by simchaba** [comment]
Le contenu du live transcript correspond au fichier de sous-titre sélectionné. Il ne peut donc pas être dissocié.

**Comment by julianastoria** [comment]
Issue à nouveau relevée lors de l'audit du 16/01/2019

**Comment by armonyaltinier** [comment]
Problème réglé.
