### ISSUE TITLE
[Dev] Non-lisibilité des boutons du player à l'agrandissement

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#16]
Lors de l'agrandissement sur Firefox (Affichage / Zoom / Zoom texte seulement), les boutons sont tronqués et il est difficile d'en connaître leur fonction et de les contrôler. 
> [Critère 10.4 [AA] Dans chaque page web, le texte reste-t-il lisible lorsque la taille des caractères est augmentée jusqu'à 200%, clicmoins (hors cas particuliers) ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-10-4)

Pour voir les boutons en entier, il faudrait supprimer l'`overflow: hidden` dans la classe `.mfp-wrapper .control-bar .right-part button` ainsi les boutons ne seraient plus contraints en largeur et hauteur. Il faut également supprimer le `width: 38px` et ajouter un `padding: 0 .13em` pour avoir un espacement suffisant entre les boutons.

**Comment by simchaba** [comment]
Il est préférable de faire un zoom sur l'ensemble des éléments (comportement par défaut des navigateurs) et pas uniquement texte. La css a été mis à jour comme demandé, mais ne peut garantir du coup un affichage correcte des sous-titres du au contrainte d'affichage
