### ISSUE TITLE
[Dev] Renforcer l'outline du slider son et progressbar durée

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#17]
À la prise de focus au clavier sur le slider son et le progressbar durée, l'outline par défaut est bien présent. 
Afin d'uniformiser et de faciliter son repérage, il serait pertinent de renforcer l'outline avec une bordure jaune comme sur les boutons.
Ex :
```
.ui-state-default:focus, 
.ui-widget-content .ui-state-default:focus {
   outline-color: yellow; 
   outline-style: solid; 
   outline-width: 1px;
}
```

**Comment by simchaba** [comment]
L'outline est mis à jour de manière uniforme
