### ISSUE TITLE
[Dev] Ajouter l'indication que les versions textes de la vidéo HTML et TXT s'ouvrent en nouvelle fenêtre

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#19]
Ajouter l'indication d'ouverture de nouvelle fenêtre dans chaque libellé : 
`<span class="mfp-icon-txt">Version texte de la vidéo TXT (nouvelle fenêtre)</span>` 

ou avec un texte caché accessible en utilisant une classe `.ui-helper-hidden-accessible` par exemple : 
`<span class="mfp-icon-txt">Version texte de la vidéo TXT <span class="ui-helper-hidden-accessible">(nouvelle fenêtre)</span></span>` 

ou en dernier ressort en ajoutant un attribut `title` : 
`<span class="mfp-icon-txt" title="Version texte de la vidéo TXT (nouvelle fenêtre)">Version texte de la vidéo TXT</span>`
> [Critère 13.2 [A] Dans chaque page web, pour chaque ouverture de nouvelle fenêtre, l'utilisateur est-il averti ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-13-2)

**Comment by simchaba** [comment]
L'intitulé du titre est dans le fichier de traduction, il a été ajouté avant, on a donc (nouvelle fenêtre) Version Texte de la vidéo TXT|HTML
