### ISSUE TITLE
[Dev] Actualiser l'intitulé bouton langue des signes

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#20]
Actuellement l'intitulé du bouton Langue des signes n'est pas pertinent ("Langue des signes active") puisqu'il indique qu'il est actif quelque soit l'état activé ou pas.
> [Critère 13.12 [A] Dans chaque page web, pour chaque contenu cryptique (art ASCII, émoticon, syntaxe cryptique) ayant une alternative, cette alternative est-elle pertinente ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-13-12)

Actualiser le `title` et tooltip du bouton en fonction de l'état du bouton soit : "Activer langue des signes" ou "Désactiver langue des signes"

**Comment by simchaba** [comment]
L'intitulé du bouton est donné par le fichier de traduction qui y inclus "Langue des signes active", l'intitulé a été modifié par "Langue des signes" afin d'être comme tous les autres bouton, uniquement une description du bouton et pas de l'action
