### ISSUE TITLE
[Dev] Vocalisation erronée au lecteur d'écran de la durée sur le slider de la ProgressBar

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#22]
Les lecteurs d'écran vocalisent inutilement les heures même quand la durée de la vidéo ne dépasse pas l'heure. Ils vocalisent par exemple la durée `0:30 / 2:51` par "_**minuit** 0 minutes 30 secondes de **minuit** 2 minutes 50 et 1 secondes_". 
> [Critère 7.1 [A] Chaque script est-il, si nécessaire, compatible avec les technologies d'assistance ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-7-1)

Il faut s'assurer que les valeurs de l'attribut `aria-valuetext` du slider `.ui-slider-handle` correspondent bien aux valeurs des classes `.timer-current` et `.timer-duration` Ainsi, la vocalisation sera conforme à l'affichage.

Testé avec : 
NVDA 2018 1.1 + FF 59.0.2
JAWS 18.0.4534 + FF 59.0.2

**Comment by simchaba** [comment]
Est-ce qu'il serait possible d'avoir plus de précision sur quels éléments doivent être modifié.

**Comment by ldzintegratore** [comment]
Il existe une barre de progression (durée), un slider donne le temps passé dans l'attribut `aria-valuetext`.
C'est cette valeur qui doit être modifiée car elle est plus "verbeuse" que celles du timer (`.timer-current` et `.timer-duration`) affiché à côté du slider volume. Il faudrait donc faire en sorte que la valeur dans `aria-valuetext` soit les mêmes que celles affichées dans `.timer-current` et `.timer-duration`. Ainsi à la vocalisation il n'y aurait plus de soucis.
Note : quand la durée ne dépasse pas 59 secondes ou 59 minutes, il faudrait pouvoir entendre que "59 secondes" ou "59 minutes" et non "minuit zéro minutes 59 secondes" ou "minuit 59 minutes..."

**Comment by simchaba** [comment]
La progression a été update. Pour les minutes lorsque la durée est inférieur à 1 minute j'ai mi 0:ss à la place de 00:ss sinon le lecteur aria va lire un nombre est pas une durée
