### ISSUE TITLE
[Dev] Personnalisation des sous-titres : non restitution à la vocalisation du lecteur d'écran des options dans un select non déplié sur JAWS.

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#24]
Lors de l'accès à la boite de personnalisation des sous-titres, le lecteur d'écran JAWS 18.2.4534 ne vocalise pas à la navigation par les flèches du clavier, les `options` dans les `select` non dépliés des différents paramètres. La restitution se fait uniquement quand le `select` est déplié.

Testé avec : 
NVDA 2018 1.1 + FF 59.0.2
JAWS 18.0.4534 + FF 59.0.2

L'implémentation est pourtant correcte. A retester ultérieurement lorsque le problème de compatibilité entre JAWS et Firefox sera réglé.
Voir [Bugtracker 1459022](https://bugzilla.mozilla.org/show_bug.cgi?id=1459022)

Avec la dernière version de JAWS2018.1804.26 ILM cela fonctionne mais ne fait pas partie de la [base de référence](https://references.modernisation.gouv.fr/rgaa-accessibilite/base-de-reference.html)

**Comment by armonyaltinier** [comment]
Le lecteur a évolué, issue non pertinente désormais.
