### ISSUE TITLE
[Dev] Les tooltips utilisés sur les boutons ne respectent pas le motif de conception WAI-ARIA

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#25]
Lors de la navigation au clavier par la touche [TAB], des tooltip apparaissent et renseignent sur la fonction des boutons. Il existe un [motif de conception WAI-ARIA pour les tooltip](https://www.w3.org/TR/wai-aria-practices/#tooltip) pour ce composant interactif qu'il faut suivre pour qu'il soit accessible.
> [Critère 7.1 [A] Chaque script est-il, si nécessaire, compatible avec les technologies d'assistance ?](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#crit-7-1)

Il manque un `role="tooltip"` sur l’élément conteneur. Les `aria-describedby` présents, ne sont pas liés à un ID sur l’élément conteneur avec `role="tooltip"`. 
A chaque survol ou à chaque passage au focus, les `aria-describedby` s’incrémentent, il faudra faire attention si cela perdure à ce que les `ID` correspondent bien.

**Comment by simchaba** [comment]
Les tooltips ont été ajouté en extra en utilisant ceux fournis par Jquery UI.
Il apparait que ceux-ci ne sont pas ARIA Compliant, les tooltips sont donc désactivés et doivent être ajoutés en futur feature dans la mesure où un développement lourd et nécessaire et pas une simple activation d'une fonction existante.
