### ISSUE TITLE
[Dev] Amélioration des dimensions de l'outline du bouton Lecture/Pause et du Volume

### ISSUE THREAD

**Issue by ldzintegratore** [mfpaccessibilite/MFP_AccessPlayer#27]
La hauteur de l'outline des boutons Lecture/Pause et Volume à la prise du focus pourrait être améliorée et en cohérence avec les autres boutons en **supprimant la position relative** via CSS :

Bouton Lecture/Pause :  
```
.mfp-wrapper .control-bar .left-part button.play, 
.mfp-wrapper .control-bar .left-part button.pause {}
```

**Bouton Lecture actuel** : 
![btn-play_actuel](https://user-images.githubusercontent.com/872670/40964707-1300a282-68ac-11e8-8ea3-9cff58140e76.png)
**Bouton Lecture après** :
![btn-play_apres](https://user-images.githubusercontent.com/872670/40964708-1350228a-68ac-11e8-9b34-5754e9de4f32.png)

Bouton Volume : 
```
.mfp-wrapper .control-bar .left-part .soundPart button.sound {}
```
**Bouton Volume actuel** : 
![btn-volume_actuel](https://user-images.githubusercontent.com/872670/40964709-13775490-68ac-11e8-9a6d-ebae6a4e0043.png)
**Bouton Volume après** :
![btn-volume_apres](https://user-images.githubusercontent.com/872670/40964710-13a50048-68ac-11e8-8a7a-9c555fd9d5f2.png)

**Comment by simchaba** [comment]
Issue is fixed
