### ISSUE TITLE
Prise en charge de Class selector et Type selector au format .vtt

### ISSUE THREAD

**Issue by knarf18** [mfpaccessibilite/MFP_AccessPlayer#3]
Bonjour,

j'aimerai savoir si pour le format .vtt le player prends bien en compte les Class selector ou Type selector

`video::cue(.MaClasse) {
  color: yellow;
}
video::cue(c) {
  color: yellow;
}`

J'ai beau tester rien ne fonctionne alors que

`video::cue {
  color: yellow;
}`👍 

lui fonctionne et mets bien l'intégralité du sous-titre en jaune.

[https://w3c.github.io/webvtt/#css-extensions](url)

**Comment by simchaba** [comment]
Le support du VTT est celui natif du navigateur, aucune modification n'est apportée.
Donc le support dépendra du navigateur utilisé.
