### ISSUE TITLE
[Dév] Problème de vocalisation du changement d'état sur certains boutons du lecteur vidéo.

### ISSUE THREAD

**Issue by mfpaccessibilite** [mfpaccessibilite/MFP_AccessPlayer#30]
Test NVDA 2018.3 et Jaws 2018.1808.10 sur Firefox 62.0.2 64 bits.

Pb uniquement sur NVDA.

Prise de focus OK sur certains boutons. Première vocalisation OK (par exemple : "lecture"). Une fois le bouton activé, plus aucune vocalisation (alors que le bouton se transforme en bouton pause), mais cette vocalisation revient après l'activation du bouton après avoir tabulé sur d'autres boutons.

L'implémentation dans le code est correcte, à investiguer du côté de Koena.

**Comment by julianastoria** [comment]
Issue à nouveau relevée lors de l'audit du 16/01/2019

**Comment by armonyaltinier** [comment]
Problème réglé.
