### ISSUE TITLE
Quelles différences avec Video.js ?

### ISSUE THREAD

**Issue by davids4** [mfpaccessibilite/MFP_AccessPlayer#34]
Bonjour,

Je n'ai pas encore eu la possibilité d'utiliser MFP_AccessPlayer qui a l'air très bien orienté vers les problèmes d'accessibilité pour toutes les vidéos en ligne.
Mais j'ai déjà travaillé avec Video.js qui propose également beaucoup de fonctions pour l'accessibilité :
https://blog.videojs.com/feature-spotlight-accessibility/

Ma question est :
**Quelles sont les différences entre ce plugin (mfp.js) et video.js ?**

Il semblerait que la majeur partie des initiatives de contributions de la communauté internationale soit tournée vers video.js.
Je me demande simplement s'il ne s'agit pas encore d'une tentative du secteur public Français de développer sa propre solution qui finira par tomber aux oubliettes rapidement à cause de l'absence de traction de la communauté Open Source (maintenance, mises à jour, sécu, etc...).

Ne vaut-il pas mieux intégrer des développements potentiellement spécifiques sur le plugin video.js, quitte à forker ou construire une surcouche, plutôt que de s'engager dans le développement d'une solution différente dans notre coin.... ?

Juste une idée et inquiétude de ma part lorsque je vois ce plugin et dois séléctionner la solution avec laquelle travailler. Pour l'instant, je ne suis pas rassuré par l'utilisation de mfp.js et compte probablement continuer de travailler avec video.js.

Merci d'avance pour vos réponses et commentaires.
Cordialement.

**Comment by softlion** [comment]
Il semble que video.js se soit arrêté au 16/1/2019 lol.

**Comment by armonyaltinier** [comment]
Merci @softlion pour la réponse :-) 

@davids4 : mfp.js est bien maintenu. Et video.js n'était malheureusement pas suffisamment conforme à l'accessibilité et il était difficile d'y contribuer pour améliorer le script sur ce sujet, d'où l'initiative de france.tv studio avec ce lecteur.
