### ISSUE TITLE
Sous-titres tronqués sur la version de démo

### ISSUE THREAD

**Issue by knarf18** [mfpaccessibilite/MFP_AccessPlayer#4]
Bonjour,

En continuant mes tests en local et en ligne sur votre version de démo j'ai remarqué que les sous-titres étaient tronqués (cachés par la barre de contrôle), il faut passer en plein écran et revenir en fenêtré pour avoir les sous-titres correctement (testé sur Firefox et Chrome).

Cela semble venir du style en ligne de la partie sous-titrage qui est calculé dans le fichier .js

**Comment by simchaba** [comment]
Merci d'indiquer les versions de firefox et de l'OS utilisé.
Aussi est-ce que les sous-titre tronqués apparaissent avec le fichier de démo ou bien un autre fichier?

**Comment by simchaba** [comment]
De même quels sous-titres sont tronqués? les STL, les VTT les SRT ?

**Comment by knarf18** [comment]
Firefox 58.0.1
Chrome Version 64.0.3282.140
Windows 7

Avec fichiers démo :
Sur les sous-titres SRT le texte est tronqué à moitié en hauteur que ce soit avec une ou deux lignes.
Sur les sous-titres STL cela passe sur deux lignes mais sur une ligne on perd le jambage. 

Avec fichier VTT perso c'est la même chose que pour le SRT de la version démo.
C'est même encore pire car pour les besoins de la vidéo les 3 ou 4 premiers sous-titres sont déplacés  plus haut dans le viewport en utilisant line:-6 align:middle et cela les repousse carrément en dessous de la barre de contrôle donc ils sont presque invisibles.

Cette syntaxe fonctionne par contre normalement dans les lecteurs par défaut des deux navigateurs, j'ai bien les sous-titres positionnés bien plus haut comme prévu.

**Comment by simchaba** [comment]
Problem was introduced by the responsive menu-bar that can now go on more than 1 line on small screen. Code has been updated on dev Branch, will be part of the next merge on master

**Comment by armonyaltinier** [comment]
Voir #6

**Comment by simchaba** [comment]
Merci de tester le code de la branche dev.

Comme indiqué le code de la branche Master n’est pas à jour et attend d’être merge

Le code de la branche Dev vient d’être testé et aucun problème.
