### ISSUE TITLE
Fenêtres modales ne se fermant pas automatiquement.

### ISSUE THREAD

**Issue by julianastoria** [mfpaccessibilite/MFP_AccessPlayer#40]
Lorsque nous activons un lien sur les fenêtres modales concernant les sous-titres ou la transcription textuelle, la fenêtre modale ne se ferme pas (clavier et souris). Il faut uniquement appuyer sur échap pour en sortir.
![fenetres](https://user-images.githubusercontent.com/30338301/51919989-cd932900-23e4-11e9-82c8-578ff4a2e08d.png)

**Comment by armonyaltinier** [comment]
Issue non pertinente. Fermée.
