### ISSUE TITLE
Restructure directories and files to facilitate AccessPlayer personalization

### ISSUE THREAD

**Issue by armonyaltinier** [mfpaccessibilite/MFP_AccessPlayer#45]
Some CSS is present in different HTML and JS files, it would be easier to split the code in a more efficient way. The objective is to allow the creation of a different version in a few minutes.

Here is a proposal for an optimized tree view:
* /content
   * /caption
   * /infos
   * /transcripts
   * /videos
   * fr.html 
* /plugin
   * /resourceSpace/smartplayer
   * /wordpress/mfp-access-player
* /script
   * /lang
   * /lib
   * /trackreader
   * player.js
* /theme
   * /ftv_access
   * /blue
   * /green
   * template.md
* [all existing files + 1 per theme]

**Comment by simchaba** [comment]
The structure doesn't fit. Plugin are separated as this include code of the player itself to be added as plugin in wordpress or resourceSoace.
Also content folder for the different videos, transcript etc.. shouldn't exists, as this is just attended for demo purpose. People using the player will refer to their own path for each files and elements shouldn't be in a specific folder for the player to work.

**Comment by simchaba** [comment]
The following structure would work as it's leaving the player separated from the demo content and not all mixed together
/MFP_AccessPlayer
	/infos	<	html pages of the about box of the player
		/en.html
		/fr.html
	/lang	<	translations of the player
		/en.js
		/fr.js
	/stylesheets	<	stylesheets example for the player
		/ftv_access.css
		/blue.css
		/green.css
		/fonts	< contains icomoon font for the player used in the stylesheets
	/sass	< sass source for the stylesheets of the player
	/trackreader	<	plugin for the player to support specific text track format like STL
	MFP_AccessPlayer.js < player main script
/demo
	/demo.html	< demo page using local player script
	/demo-cdn.html < demo page using CDN hosted player script
	/demo_contents < folder with demo text-track, video, transcript
		/captions
		/transcripts
		/videos
/plugin
	/resourceSpace
	/wordpress

**Comment by armonyaltinier** [comment]
> The structure doesn't fit. Plugin are separated as this include code of the player itself to be added as plugin in wordpress or resourceSoace.
> Also content folder for the different videos, transcript etc.. shouldn't exists, as this is just attended for demo purpose. People using the player will refer to their own path for each files and elements shouldn't be in a specific folder for the player to work.

I don't understand. The /plugin directory is already separated in the present tree view, and remains separated in the new structure…

**Comment by armonyaltinier** [comment]
> The following structure would work as it's leaving the player separated from the demo content and not all mixed together
> /MFP_AccessPlayer
> /infos < html pages of the about box of the player
> /en.html
> /fr.html
> /lang < translations of the player
> /en.js
> /fr.js
> /stylesheets < stylesheets example for the player
> /ftv_access.css
> /blue.css
> /green.css
> /fonts < contains icomoon font for the player used in the stylesheets
> /sass < sass source for the stylesheets of the player
> /trackreader < plugin for the player to support specific text track format like STL
> MFP_AccessPlayer.js < player main script
> /demo
> /demo.html < demo page using local player script
> /demo-cdn.html < demo page using CDN hosted player script
> /demo_contents < folder with demo text-track, video, transcript
> /captions
> /transcripts
> /videos
> /plugin
> /resourceSpace
> /wordpress

I think you need to edit your message in order to make the sublists appear. I don't understand your structure… 24 directories ?! Unusable…

**Comment by armonyaltinier** [comment]
Anyway, we need a /theme directory… For the player itself, and the demo page. Some people want to use the player in a preformatted page. The demo page could be used this way.

**Comment by simchaba** [comment]
Please see corrected structure.
Theme are only CSS nothing else. so should only exist in the css folder of the player. 
Javascript library only include demo page on the side for people willing to use theme as it is. So demo content shouldn't be inside the player directors infrastructure

**Comment by armonyaltinier** [comment]
> Please see corrected structure.
OK, I see… it's clearer now. But not sure to agree according to the users' point of view, even if I understand your dev's point of you. Need to ckeck.

> Theme are only CSS nothing else. so should only exist in the css folder of the player.
It should be, but it's not the case! Some code is included in the JS files, and make some customisation impossible without changing the JS.

> Javascript library only include demo page on the side for people willing to use theme as it is. So demo content shouldn't be inside the player directors infrastructure
Some people (and france.tv studio had a precise request) want to use the demo page as it, to embed the player in a single customizable page.

**Comment by simchaba** [comment]
For the themes, if some specific code is needed, then it's not a theme as it's adding then functionality, so either it is added to the layer for every theme and some don't use it (display: none) for example, or possible to disable thru the loading options of the player.

Concerning demo page, it will never be inside the structure of the player, always outside with reference to load the element in the player directory. Also we can not put on the repository video as repository is supposed to only be for code and can not host large files.

**Comment by armonyaltinier** [comment]
> Concerning demo page, it will never be inside the structure of the player, always outside with reference to load the element in the player directory. Also we can not put on the repository video as repository is supposed to only be for code and can not host large files.

In my proposal, the demo file could easily be outside the player directory, and you're right concerning the video directory. But it should be the same for the other resources:
* captions
* transcripts
* …

The plugin directory, however, should ould remain in the Player directory, and the theme directory too.
Imagine you download a project such as WordPress and have to download the themes and plugins separately. It would not be handy and a bit weird, don't you think?

Here is a conter-proposal:
* /MFP_AccessPlayer
   * /info
      * fr.html
      * en.html
   * /lang
      * fr.js
      * en.js
   * /plugin
      * /resourceSpace/smartplayer
      * /wordpress/mfp-access-player
   * /script
      * /lang
      * /lib
      * /trackreader
      * player.js
   * /theme
      * /ftv_access
      * /blue
      * /green
      * template.md
   * [all other existing files]
* /content
   * /caption
   * /transcripts
   * /videos
* [1 demo file.html per theme]

**Comment by simchaba** [comment]
Plugins are outside the scope of the Player therefore shouldn't be in the main directory, they should in fact have their own repository to be completely clean and just refer to them in the ReadMe. The recommended way to use the plugin is with the CDN, therefore the code of the player isn't loaded from the plugin but from the CDN.

Concerning name of the folder theme, this is the same as CSS. we could rename is that way if you want, but this is completely the same. Also it is important to keep the SASS files as if people want to make custom theme they will need the sass files to customize the theme faster
