### ISSUE TITLE
Perte de la barre des contrôles en mode plein écran sur Firefox 

### ISSUE THREAD

**Issue by knarf18** [mfpaccessibilite/MFP_AccessPlayer#5]
Bonjour,

En passant en mode plein écran sous Firefox pour résoudre le problème des sous-titres tronqués, je me suis rendu compte que l'on perdait la barre des contrôles, alors que sous Chrome elle est bien présente.

Firefox 58.0.1
Chrome Version 64.0.3282.140
Windows 7

**Comment by simchaba** [comment]
Issue Fix in dev branch will be part of the next merge
