### ISSUE TITLE
[audit site démo] Focus sur le lien france.tv access

### ISSUE THREAD

**Issue by julianastoria** [mfpaccessibilite/MFP_AccessPlayer#58]
Ceci n’est pas une non-conformité, mais le focus sur le lien « france.tv access » n’est pas bien visible. Il faudrait par exemple, changer la couleur de focus en blanc en CSS avec l’attribut outline.

**Comment by simchaba** [comment]
modifié dans le commit : 49c3663386dae43d317d23a2c61913ae901145df [49c3663]
