### ISSUE TITLE
[audit site démo] Menu disgracieux en mode mobile (320px)

### ISSUE THREAD

**Issue by julianastoria** [mfpaccessibilite/MFP_AccessPlayer#59]
Quand on réduit l’écran à 320px de large, le menu est visible, c’est donc conforme, mais pas très esthétique. Il serait utile d’optimiser la présentation du menu en le centrant par exemple.
![image](https://user-images.githubusercontent.com/30338301/69873272-2c9d2500-12b8-11ea-9a66-c527cfe2a203.png)

**Comment by simchaba** [comment]
Modifié dans le commit : 6e51a4c65b967adf0bf1b7330d5e532d99fdff09 [6e51a4c]
