### ISSUE TITLE
Affichage des sous-titres tronqué

### ISSUE THREAD

**Issue by mfpaccessibilite** [mfpaccessibilite/MFP_AccessPlayer#6]
Lors de l'activation des sous-titres par défaut, leur affichage est tronqué. En activant puis désactivant le plein écran, le problème disparaît.

De même, si on passe d'un format de sous-titre à l'autre (SRT>STL, ou inversement), le problème disparait.

**Comment by simchaba** [comment]
@mfpaccessibilite,ce bug a déjà été reporté est fixé dans dev. Merci de valider la branche dev et de la merger sur master

**Comment by mfpaccessibilite** [comment]
OK. On cale un test de conformité RGAA et un de restitution au lecteur d'écran avant fusion. Ping @armonyaltinier

**Comment by armonyaltinier** [comment]
Le problème persiste après test sur FF 59.0.2

**Comment by simchaba** [comment]
Le calcul de la hauteur disponible a été ajouté à la fin du chargement de l'interface ce qui ne devrait plus poser de problème de position des sous-titres
