### ISSUE TITLE
[audit site démo] Boutons de changement de thème

### ISSUE THREAD

**Issue by julianastoria** [mfpaccessibilite/MFP_AccessPlayer#60]
Pour permettre de s’y retrouver et de voir le choix disponible dans les thèmes proposés, il serait utile de changer le fonctionnement actuel. 1 bouton = 1 thème. Actuellement, le nom du thème disponible change selon si le bouton est sélectionné ou non.
Penser également à mettre un aria-selected=”true” sur le thème en cours d’utilisation ; avec un changement de couleur et un picto triangle pour un repère visuel du thème en cours.

**Comment by simchaba** [comment]
Modifié dans le commit : 
e81674d4becf35e612021cfbab4990d8bbdf47b9 [e81674d]
