### ISSUE TITLE
[Feature?] Comment démarrer la vidéo à une position donnée ?

### ISSUE THREAD

**Issue by softlion** [mfpaccessibilite/MFP_AccessPlayer#62]
Bonjour,
est il possible de démarrer une vidéo à, par ex, 10mn au lieu du début ?
Je ne vois pas l'option.

C'est comme quand on embed une video de france.tv, par ex https://www.france.tv/franceinfo/restezalamaison/1748305-emission-du-mercredi-27-mai-2020.html, on ne peux pas dire au lecteur de démarrer à une position donnée (celle ou on a le contenu qui nous intéresse).

Une idée ?

**Comment by armonyaltinier** [comment]
Bonjour @softlion . Désolée pour la réponse tardive.
Pour démarrer la vidéo au minutage souhaité, il faut modifier la valeur de l'option start_ts : par défaut, la valeur est à 0.
Ça fonctionne chez vous ?
